version: '3.8'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yur4ik1234/labdevops:django-compose
    container_name: django
    networks: 
      - public
    ports: 
      - 8000:8000
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    image: yur4ik1234/labdevops:monitoring-compose
    container_name: monitoring

    network_mode: host

networks: 
  public:
    driver: bridge
